apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/bpfman/bpfman-operator?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: "{{revision}}"
    build.appstudio.redhat.com/target_branch: "{{target_branch}}"
    build.appstudio.openshift.io/build-nudge-files: "hack/update_catalog.sh"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: bpfman-operator
    appstudio.openshift.io/component: bpfman-operator-bundle
    pipelines.appstudio.openshift.io/type: build
  name: bpfman-operator-bundle-on-push
  namespace: lucarval-tenant
spec:
  params:
    - name: build-source-image
      value: "true"
    #- name: prefetch-input
    #  value: '{"type": "gomod", "path": "."}'
    - name: git-url
      value: "{{source_url}}"
    - name: revision
      value: "{{revision}}"
    - name: output-image
      value: quay.io/redhat-user-workloads/ocp-bpfman-tenant/bpfman-operator/bpfman-operator-bundle:{{revision}}
    - name: dockerfile
      value: Containerfile.bundle.openshift
  pipelineRef:
    name: single-arch-build-pipeline
  taskRunTemplate: {}
  workspaces:
    - name: workspace
      volumeClaimTemplate:
        metadata:
          creationTimestamp: null
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 1Gi
        status: {}
    - name: git-auth
      secret:
        secretName: "{{ git_auth_secret }}"
status: {}
